### ISSUE TITLE
Don't make the keyboard follow the camera

### ISSUE THREAD

**Issue by danielbuechele** [danielbuechele/react-360-keyboard#1]
The keyboard is displayed fixed to the camera in the lower part of the screen. After trying this in VR, it turned out to be annoying. The keyboard should rather be displayed in the middle of the screen and not follow when the camera moves.

One important thing to consider is to always show the keyboard at the center of the current view angle, to make sure the user can see the keyboard.

The position of the keyboard is set here: https://github.com/danielbuechele/react-360-keyboard/blob/master/react-360-keyboard/KeyboardModule.js#L29

**Comment by horacioh** [comment]
@danielbuechele let me know your thoughts on this!

P.S.: thanks for pointing out the actual line of code. that helped me from wasting time looking for it :)
